MANIFEST.in

This enables developers to run the tests directly from the extracted source tarball. This would be great for a future Debian package that I would like to create.

Include tests

---

MANIFEST.in

It's nice to have the README.md inside the source tarball so I can ship it as sort of a short documentation in the binary Debian packages for those who do not install the full documentation package.

Include README.md in source tarball.

---

recurrence/base.py

I ran into a the situation where rule.wkst is sometimes already a weekday instance.
This change should allow the code to work whether it's a number or an instance.

sometimes rule.wkst is a weekday instance and not a number

---

recurrence/base.py

currently the local timezone is set using the default timezone setting,
however if a different timezone has been activated for the current user
then it would be optimal to convert the date to that timezone.  if no
timezone is currently set, then it will fall back to the default
`settings.TIME_ZONE` value

use current timezone for localization

---

setup.py

If you install django-recurrence the regular way (without the -e option), Django cannot find its migrations package, because it does not get installed. The setup.py file misses this entry in the ``packages`` directive.

Update setup.py to include the migrations package

---

recurrence/static/recurrence/css/recurrence.css

These tweaks allow proper display in the Wagtail admin by explicitly applying the styles within the Django admin to override defaults from the Wagtail admin. They shouldn't affect the look in the Django admin. Thanks for your efforts. If you'd like, I could add a section to the docs for integration with Wagtail.

Minor CSS tweaks to allow display with the Wagtail CMS admin.

---

docs/usage/recurrence_field.rst
recurrence/base.py
recurrence/fields.py
tests/test_fields.py

As stated by @jpulec in #90 `dtstart` is handled according to RFC 2445 so that it always counts as the first occurrence regardless of your pattern, like when used with `between()`. This causes confusion for some users (e.g. #36, #50, #71) because it is in conflict with how `dateutil.rrule` handles `dtstart`.
With this pull request I suggest a solution which consists of:
1. The addition of an optional parameter `include_dtstart` which can be either passed to a `RecurrenceField` or a `Recurrence` instance. With `include_dtstart=False` the default behavior does not occur for the field/object so that `dtstart` no longer finds its way into the occurrence list if it does not match your recurrence pattern. Because the default behavior doesn't change if `include_dtstart` is not specified backward …

Flexible handling of dtstart incl. documentation

---

recurrence/base.py
tests/test_serialization.py

Calling deserialize('RRULE:A') would raise an AttributeError instead of DeserializationError, since the string was used incorrectly as a dict.
I added some tests to make sure DeserializationError is raised in all cases.

Bug fix in deserialize

---

recurrence/base.py

in python 3 the `__str__` method is called when converting a class to a
string (opposed to the `__unicode__` method in py2).  This change renames
the `__unicode__` method to `__str__`, so we can easily get the serialized
version of a Recurrence object and while doing so maintain py2
compatibility be wrapping the class with Django's
`python_2_unicode_compatible` decorator
for more info see https://docs.djangoproject.com/en/1.11/topics/python3/#str-and-unicode-methods

updating Recurrence class to be py3 compatible

---

.travis.yml
docs/installation.rst
recurrence/migrations/0001_initial.py
recurrence/models.py
tox.ini

* Set on_delete to CASCADE explicitly as required for django 2.0.  This mimics the default of prior django versions.
* Updated existing migration to explicitly set CASCADE.  As this was implicitly set before, this is only necessary for new users running the migration.
* Updated test suite to test django 2.0 + python 3.5.  Python 3.4 is being deprecated, so didn't add 3.4.  Happy to change if there's disagreement that we should also test 3.4.
* Updated documentation to use the as_view pattern for JavaScriptCatalog in urls.py.

Add full support for django2

---

recurrence/static/recurrence/js/recurrence-widget.js
recurrence/static/recurrence/js/recurrence.js

Depending on the current day of the month and the day you're selecting in the calendar the widget will select a day in the wrong month. 
The easiest way to explain this is through an example. 
If it is currently January 30th and I choose the date February 15th in the calendar widget March 15th will show up as the chosen date.
Checking how the date is set showed that the year is updated, then the month, then the day. 
In the January 30th example the year is updated no problem. Then the month is updated to February, but since February doesn't have a 30th the JavaScript date library automatically accounts for this by setting the date to March 2nd. Lastly the day is finally set giving us the result March 15th

Change order that month and date are set

---

recurrence/forms.py
tests/test_fields.py

This is for #89  , where a `value` of None to the `clean` method results in an error when deserializing happens.  I haven't dug deep enough to know if this is the absolute best way to fix it, but at least it prevents the TypeError.  Added a test to test_fields.py as well.  Do with this as you please  :)

added typeerror exception and test for #89

---

recurrence/forms.py

For Django 2.1 compatibility widget render method should always have renderer argument.
[Reference](https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1)

Django 2.1 compatibility fix for widget render method

---

recurrence/fields.py
recurrence/forms.py

As discussed [here](https://code.djangoproject.com/ticket/24716) the use of _get_val_from_obj inside the value_to_string method is deprecated and then removed in Django 2.
This generally not causes any problem, but trips up Django Rest Framework when using a serializer with this field.

 Django 2 compatibility fix for value_to_string 

---

recurrence/static/recurrence/css/recurrence.css
recurrence/static/recurrence/js/recurrence-widget.js

The main reason I'm suggesting this change is to better facilitate using `RecurrenceWidget` with a style reset (e.g., cleanslatecss) to get around collisions with other stylesheets.

Replace display:none with .hidden

---

recurrence/forms.py

Handle missing javascript_catalog view in django 2

---

MANIFEST.in

Using a plain wildcard `*` also includes build-artifacts like `.pyc` files in
the source tarball. This is then flagged by systems like Debian's `lintian`
which checks for clean source tarballs.

Be more selective when including assets in the source tarball.

---

setup.py

When performing a search on PyPI, no repository URL or detailed description is available for django-recurrence.
- Added long_description, which reads README.md
- Added URL to github repository

Updated to provide useful information on PyPI

---

recurrence/forms.py

Without this change, the admin loads recurrence-widget.init.js
before jquery.init.js. As a consequence, the `django.jQuery` variable
isn't created yet and the following error happens:
Uncaught TypeError: django.jQuery is not a function at recurrence-widget.init.js:1
With this change, the admin loads JS scripts in the correct order.
Refs #142.

Declare dependency on the admin's jQuery.js

---

.travis.yml
docs/conf.py
recurrence/base.py
recurrence/compat.py
recurrence/fields.py
recurrence/forms.py
recurrence/migrations/0001_initial.py
recurrence/settings.py
setup.py
tests/test_settings.py
tests/test_tz.py
tox.ini

Remove old Python and Django compatibility code as discussed in django-recurrence issue #144 
Python 2.7 should be deprecated from web projects and Django 2.0 is EOL.

Clean up deprecated code

---

recurrence/forms.py

I encountered problems in the admin of a Wagtail/Django Website, when upgrading to the latest packages and narrowed down the error to django-recurrence 1.10.0
Django says: `[20/Jul/2019 13:16:25] "GET /static/vendor/jquery/jquery.js HTTP/1.1" 404 1691`
Chrome says: `GET http://0.0.0.0:8001/static/vendor/jquery/jquery.js net::ERR_ABORTED 404 (Not Found)`
Firefox says: `The script from “http://0.0.0.0:8001/static/vendor/jquery/jquery.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`
For testing purposes I set up a fresh Django 2.2.
Django puts its admin's jQuery per default to `static/admin/js/vendor/jquery/jquery.(min.)js`.
After my changes `make testall` results are still positive.
Thank you very much for this project!
Gabriel

Fix: 404 in browsers console when using recurrence in django admin

---

recurrence/base.py

When you deserialize recurrence from string:
```
r = deserialize('DTSTART:20201015T000000\nRRULE:FREQ=WEEKLY;COUNT=30;INTERVAL=1;WKST=MO')
```
And then try to create a recurrence object:
```
Recurrence.objects.create_from_recurrence_object(r)
```
You'll get an error:
Because `r.wkst` is a `Weekday` object, but it should be an integer.

Weekday should be int, not an object

---

recurrence/base.py
tests/test_serialization.py

There's an issue #158 concerning this problem. I ran into it recently too. It looks like a small fix that deserves to be implemented.

Deserialize recurrences with multiple comma-separated exclusion dates

---

recurrence/static/recurrence/css/recurrence.css

A cosmetic PR that improves readability of the admin widget in dark mode.
Before:
After:

change label font color to white in dark mode

---

docs/installation.rst

Fix: The current installation instructions produce an error as described in [this PR](https://github.com/Tivix/django-rest-auth/issues/659). Updating the import statement to align with latest version of Django.

fix: update import statement to align with latest version of Django
